# Generated by Django 3.1.6 on 2021-02-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210223_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefriend',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.profile'),
        ),
    ]
