# Generated by Django 3.1.6 on 2021-02-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210223_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFriend',
            new_name='FollowingFollowers',
        ),
    ]
