# Generated by Django 3.1.6 on 2021-02-23 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20210223_2329'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='followingfollowers',
            name='unique_followers',
        ),
        migrations.RemoveField(
            model_name='followingfollowers',
            name='follower_profile',
        ),
        migrations.RemoveField(
            model_name='followingfollowers',
            name='following_profile',
        ),
        migrations.AddField(
            model_name='followingfollowers',
            name='follower_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followingfollowers',
            name='following_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='followingfollowers',
            constraint=models.UniqueConstraint(fields=('following_user', 'follower_user'), name='unique_followers'),
        ),
    ]
