# Generated by Django 3.1.6 on 2021-02-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210223_2348'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='followingfollowers',
            name='unique_followers',
        ),
    ]
